To change param #46 failed, probably due to extra whitespaces ?
Not sure if extra whitespace are the problem, but I didn't see any syntax error...

I always got exceptions like

2015-12-16 22:18:47.071 [WARN ] [e.jetty.servlet.ServletHandler] - /services/habmin/zwave/set/nodes/node84/parameters/configuration46
java.lang.RuntimeException: java.lang.NumberFormatException: For input string: "Enable                          "
        at org.atmosphere.handler.ReflectorServletProcessor.onRequest(ReflectorServletProcessor.java:163) ~[na:na]
        at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:206) ~[na:na]